---
# Running with file base sqlite DB -> my.db
spring:
  config.activate.on-profile: sqlite
  datasource:
    url: "jdbc:sqlite:C:\\LAVKHERWA\\pfm-common-utilities\\testing-cap\\my.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
      max-lifetime: 0
---

# Running with in-memory sqlite DB
spring:
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always 
    hikari:
      maximum-pool-size: 1
      max-lifetime: 0      
 